; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SendMode, Input
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

;;@Ahk2Exe-UpdateManifest 1
;@Ahk2Exe-SetMainIcon build.ico
;@Ahk2Exe-SetCompanyName Congo Cloud Computer
;@Ahk2Exe-SetCopyright 2023 CongoCloudComputer
;@Ahk2Exe-SetDescription Select HTTPD Root directory simply
;@Ahk2Exe-SetFileVersion 1.0.0
;@Ahk2Exe-SetInternalName RootSelector
;@Ahk2Exe-SetLegalTrademarks 3C-Numeric
;@Ahk2Exe-SetProductName httpd selector
;@Ahk2Exe-SetVersion 1.0

#Include, selector_cfg.ahk

HTTPD_PATH          := ""
CURRENT_FOLD        := ""

Menu Tray, Icon, shell32.dll, 10

Gui Main: New, +LabelMain +hWndhMainWnd -MaximizeBox
Gui Color, White
Gui Add, DropDownList, hWndhDDLItems vDDLItems gchangeEvent x8 y108 w333
Gui Font, s13
Gui Add, Text, x464 y320 w236 h25 +0x200 +Center, Dev - HTTPD - ROOT - SELECTOR
Gui Font, cGreen s8
Gui Add, Text, hWndhTxtC2 vTxtC2 x11 y64 w332 h37, c:\
Gui Font
Gui Add, Button, hWndhBtn vBtn gSelectFold x196 y132 w145 h23, &Select new directory
Gui Add, Button, hWndhBtn2 vBtn2 gOpenControlPanale x130 y132 w60 h23, &cPanel
Gui Font, s14
Gui Add, Text, x15 y0 w322 h36 +0x200 +Center, Dev HTTPD ROOT Directory
Gui Font
Gui Add, Text, x16 y32 w318 h33, Sélectionner un répertoire de`ntravail Root rapide pour votre projet web Xampp ou Wamp
Gui Add, Text, x8 y134 w120 h23 +0x200, Congo Cloud Computer

init()

Gui Show, w351 h165, server root selector
Return

init() {
  global
  CURRENT_FOLD  := ""
  HISTORY_LIST  := ""
  HTTPD_PATH    := ""

  FileRead, CURRENT_FOLD, current_directory.txt
  FileRead, HTTPD_PATH, httpd_path.txt

  Loop, Read, folders.txt, path
  {
    if (StrLen(Trim(A_LoopReadLine)) > 0) {
      HISTORY_LIST := A_LoopReadLine "||" HISTORY_LIST
    }
  }

  setCurrentText(CURRENT_FOLD)
  GuiControl,, DDLItems , %HISTORY_LIST%
}

setCurrentText(pathText) {
  global

  ; save to file
  if (StrLen(Trim(pathText)) > 0) {
    file := FileOpen("current_directory.txt", "w")
    file.Write(pathText)
    file.Close()
  }

  if (StrLen(pathText) > 50) {
    part1     := SubStr(pathText, 1, 50)
    part2     := SubStr(pathText, 51)
    pathText  := part1 "`n" part2
  }
  GuiControl,, TxtC2 , --> %pathText%
}

setFold() {
  global

  Replace := False
  With    := ""
  HTTPD_FILE := ""

  ; Loop, Read, httpd.conf, path
  Loop, Read, %HTTPD_PATH%, path
    {
      Jump := False
      For Key, Value in SYMBOL
        {
          Jump := False
          if (A_LoopReadLine = Value.comment) {
            Replace     := True
            With        := Format(Value.value, CURRENT_FOLD)
            HTTPD_FILE  .= A_LoopReadLine "`n"
            Jump        := True
            Break
          }
          else if (Replace = True) {
            HTTPD_FILE  .= With "`n"
            Replace     := False
            Jump        := True
            Break
          }
        }
      
      if (Jump = True)
        Continue

      if (Replace = False) {
        HTTPD_FILE .= A_LoopReadLine "`n"
      }
    }
  
  setCurrentText(CURRENT_FOLD)
  ; file := FileOpen("httpd.conf", "w")
  file := FileOpen(HTTPD_PATH, "w")
  file.Write(HTTPD_FILE)
  file.Close()
}

changeEvent(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
  global
  GuiControlGet, OutputVar ,, DDLItems
  setCurrentText(OutputVar)
  CURRENT_FOLD := OutputVar
  setFold()
}

SelectFold(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
  global
  ISINFOFLD := False

  FileSelectFolder, OutputVar ,,, Selectionner votre repertoire de travail.
  if (StrLen(OutputVar) = 0)
    Return

  Loop, Read, folders.txt, path
    {
      if (Trim(A_LoopReadLine) = OutputVar) {
        ISINFOFLD := True
      }
    }
  if (ISINFOFLD = False) {
    OutputVar := Trim(OutputVar)
    OutputVar := StrReplace(OutputVar, """" , "")
    FileAppend, `n%OutputVar%, folders.txt
    GuiControl,, TxtC2 , --> %OutputVar%
    GuiControl,, DDLItems, %OutputVar%
    CURRENT_FOLD := OutputVar
    setCurrentText(OutputVar)
  }
  else {
    setCurrentText(OutputVar)
    CURRENT_FOLD := OutputVar
  }

  setFold()
}

OpenControlPanale() {
  global
  xpath := SERVER.xampp.panel

  if (FileExist(xpath)) {
    ; RUN AS ADMIN
    Run *RunAs "%xpath%" /restart
  } else {
    msgbox 16, Not Found, Aucun paneau de contre XAMPP trouver sur le chemin %xpath%
  }
}

MainEscape:
MainClose:
    ExitApp
